# \u4F7F\u7528\u65E5\u5FD7\u6A21\u5757
modulelist=com.p6spy.engine.logging.P6LogFactory

# \u4F7F\u7528 Slf4j \u8F93\u51FA\uFF08\u4EA4\u7ED9 Spring Boot \u65E5\u5FD7\u7CFB\u7EDF\uFF09
appender=com.p6spy.engine.spy.appender.Slf4JLogger

# \u5355\u884C\u683C\u5F0F
#logMessageFormat=com.p6spy.engine.spy.appender.SingleLineFormat

# \u9A71\u52A8\u914D\u7F6E
driverlist=com.mysql.cj.jdbc.Driver

# \u4F7F\u7528\u81EA\u5B9A\u4E49\u65E5\u5FD7\u683C\u5F0F
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
customLogMessageFormat=%(sqlSingleLine)

# \u6392\u9664\u4E0D\u9700\u8981\u7684\u7C7B\u522B
excludecategories=commit,rollback,resultset,result

# \u53EA\u8BB0\u5F55\u5B9E\u9645\u6267\u884C\u7684SQL\u8BED\u53E5\uFF08\u901A\u8FC7\u6B63\u5219\u8868\u8FBE\u5F0F\u8FC7\u6EE4\uFF09
sqlexpression=^(select|insert|update|delete).*

# \u65E5\u671F\u683C\u5F0F
dateformat=yyyy-MM-dd HH:mm:ss

